"""
Shared test fixtures for agentic_kg_api tests.

Generated by test-generator agent.
"""

import pytest
from unittest.mock import MagicMock, patch
from fastapi.testclient import TestClient

from agentic_kg_api.main import app
from agentic_kg_api.dependencies import get_repo, get_search, get_relations


# =============================================================================
# Mock Dependencies
# =============================================================================


@pytest.fixture
def mock_repo():
    """Create a mock Neo4jRepository."""
    repo = MagicMock()
    repo.verify_connectivity.return_value = True
    return repo


@pytest.fixture
def mock_search_service():
    """Create a mock SearchService."""
    return MagicMock()


@pytest.fixture
def mock_relation_service():
    """Create a mock RelationService."""
    return MagicMock()


@pytest.fixture
def client(mock_repo, mock_search_service, mock_relation_service):
    """
    Create a FastAPI TestClient with all dependencies overridden.

    Dependencies are replaced with mocks to avoid needing a real
    Neo4j database or other external services.
    """
    app.dependency_overrides[get_repo] = lambda: mock_repo
    app.dependency_overrides[get_search] = lambda: mock_search_service
    app.dependency_overrides[get_relations] = lambda: mock_relation_service
    yield TestClient(app)
    app.dependency_overrides.clear()


# =============================================================================
# Sample Data Factories
# =============================================================================


def make_problem(**kwargs):
    """Create a mock Problem object with sensible defaults."""
    from unittest.mock import MagicMock

    p = MagicMock()
    p.id = kwargs.get("id", "prob-001")
    p.statement = kwargs.get("statement", "How to improve transformer efficiency?")
    p.domain = kwargs.get("domain", "NLP")
    p.status = kwargs.get("status", MagicMock(value="open"))
    p.created_at = kwargs.get("created_at", None)
    p.updated_at = kwargs.get("updated_at", None)
    p.extraction_metadata = kwargs.get("extraction_metadata", None)
    p.evidence = kwargs.get("evidence", None)
    p.assumptions = kwargs.get("assumptions", [])
    p.constraints = kwargs.get("constraints", [])
    p.datasets = kwargs.get("datasets", [])
    p.metrics = kwargs.get("metrics", [])
    p.baselines = kwargs.get("baselines", [])
    return p


def make_paper(**kwargs):
    """Create a mock Paper object with sensible defaults."""
    from unittest.mock import MagicMock

    p = MagicMock()
    p.doi = kwargs.get("doi", "10.1234/test.2024")
    p.title = kwargs.get("title", "Test Paper Title")
    p.authors = kwargs.get("authors", ["Author A", "Author B"])
    p.year = kwargs.get("year", 2024)
    p.venue = kwargs.get("venue", "NeurIPS")
    p.abstract = kwargs.get("abstract", "This is a test abstract.")
    p.arxiv_id = kwargs.get("arxiv_id", "2401.00001")
    p.pdf_url = kwargs.get("pdf_url", "https://arxiv.org/pdf/2401.00001")
    p.citation_count = kwargs.get("citation_count", 42)
    return p


def make_search_result(problem=None, score=0.95, match_type="hybrid"):
    """Create a mock search result."""
    from unittest.mock import MagicMock

    r = MagicMock()
    r.problem = problem or make_problem()
    r.score = score
    r.match_type = match_type
    return r
