"""
Tests for agentic_kg_api.config -- API configuration.

Generated by test-generator agent.
"""

import pytest
from agentic_kg_api.config import APIConfig, get_api_config, reset_api_config


class TestAPIConfig:
    """Tests for APIConfig."""

    def test_defaults(self):
        """Config has sensible defaults."""
        config = APIConfig()
        assert config.host == "0.0.0.0"
        assert config.port == 8000
        assert config.debug is False
        assert "http://localhost:3000" in config.cors_origins

    def test_requires_auth_false_by_default(self):
        """Auth not required when API_KEY is empty."""
        config = APIConfig()
        assert config.requires_auth is False

    def test_requires_auth_true_with_key(self, monkeypatch):
        """Auth required when API_KEY is set."""
        monkeypatch.setenv("API_KEY", "secret123")
        config = APIConfig()
        assert config.requires_auth is True

    def test_loads_from_environment(self, monkeypatch):
        """Config loads values from env vars."""
        monkeypatch.setenv("API_HOST", "127.0.0.1")
        monkeypatch.setenv("API_PORT", "9000")
        monkeypatch.setenv("API_DEBUG", "true")
        monkeypatch.setenv("CORS_ORIGINS", "http://myapp.com")
        config = APIConfig()
        assert config.host == "127.0.0.1"
        assert config.port == 9000
        assert config.debug is True
        assert config.cors_origins == ["http://myapp.com"]

    def test_singleton_reset(self):
        """get_api_config returns singleton; reset clears it."""
        reset_api_config()
        config1 = get_api_config()
        config2 = get_api_config()
        assert config1 is config2
        reset_api_config()
        config3 = get_api_config()
        assert config1 is not config3
        reset_api_config()  # cleanup
