"""
Tests for agentic_kg_api.routers.papers -- Paper list/detail endpoints.

Generated by test-generator agent.
"""

import pytest
from unittest.mock import MagicMock

from agentic_kg.knowledge_graph.repository import NotFoundError

from tests.conftest import make_paper


# =============================================================================
# GET /api/papers -- List Papers
# =============================================================================


class TestListPapers:
    """Tests for GET /api/papers."""

    def test_list_papers_empty(self, client, mock_repo):
        """Returns empty list when no papers exist."""
        mock_session = MagicMock()
        mock_result = MagicMock()
        mock_result.__iter__ = MagicMock(return_value=iter([]))
        mock_session.run.return_value = mock_result
        mock_repo.session.return_value.__enter__ = MagicMock(return_value=mock_session)
        mock_repo.session.return_value.__exit__ = MagicMock(return_value=False)

        response = client.get("/api/papers")
        assert response.status_code == 200
        data = response.json()
        assert data["papers"] == []
        assert data["total"] == 0

    def test_list_papers_returns_summaries(self, client, mock_repo):
        """Returns paper summaries."""
        mock_session = MagicMock()
        record1 = {
            "p": {
                "doi": "10.1234/a",
                "title": "Paper A",
                "authors": ["Auth1"],
                "year": 2024,
                "venue": "ICML",
            }
        }
        record2 = {
            "p": {
                "doi": "10.1234/b",
                "title": "Paper B",
                "authors": [],
                "year": 2023,
                "venue": None,
            }
        }
        mock_result = MagicMock()
        mock_result.__iter__ = MagicMock(return_value=iter([record1, record2]))
        mock_session.run.return_value = mock_result
        mock_repo.session.return_value.__enter__ = MagicMock(return_value=mock_session)
        mock_repo.session.return_value.__exit__ = MagicMock(return_value=False)

        response = client.get("/api/papers")
        assert response.status_code == 200
        data = response.json()
        assert len(data["papers"]) == 2
        assert data["papers"][0]["doi"] == "10.1234/a"
        assert data["papers"][0]["title"] == "Paper A"

    def test_list_papers_with_pagination(self, client, mock_repo):
        """Supports limit and offset."""
        mock_session = MagicMock()
        mock_result = MagicMock()
        mock_result.__iter__ = MagicMock(return_value=iter([]))
        mock_session.run.return_value = mock_result
        mock_repo.session.return_value.__enter__ = MagicMock(return_value=mock_session)
        mock_repo.session.return_value.__exit__ = MagicMock(return_value=False)

        response = client.get("/api/papers?limit=10&offset=5")
        assert response.status_code == 200
        data = response.json()
        assert data["limit"] == 10
        assert data["offset"] == 5

    @pytest.mark.parametrize("limit", [0, -1, 501])
    def test_list_papers_invalid_limit(self, client, mock_repo, limit):
        """Rejects invalid limit values."""
        response = client.get(f"/api/papers?limit={limit}")
        assert response.status_code == 422


# =============================================================================
# GET /api/papers/{doi} -- Get Paper Detail
# =============================================================================


class TestGetPaper:
    """Tests for GET /api/papers/{doi}."""

    def test_get_existing_paper(self, client, mock_repo):
        """Returns paper detail for existing DOI."""
        paper = make_paper(doi="10.1234/test", title="Test Paper")
        mock_repo.get_paper.return_value = paper
        response = client.get("/api/papers/10.1234/test")
        assert response.status_code == 200
        data = response.json()
        assert data["doi"] == "10.1234/test"
        assert data["title"] == "Test Paper"
        assert data["abstract"] == "This is a test abstract."
        assert data["arxiv_id"] == "2401.00001"

    def test_get_nonexistent_paper_returns_404(self, client, mock_repo):
        """Returns 404 for nonexistent DOI."""
        mock_repo.get_paper.side_effect = NotFoundError("not found")
        response = client.get("/api/papers/10.9999/missing")
        assert response.status_code == 404
        assert "Paper not found" in response.json()["detail"]

    def test_get_paper_url_decoded_doi(self, client, mock_repo):
        """DOI is URL-decoded before lookup."""
        paper = make_paper(doi="10.1234/special chars")
        mock_repo.get_paper.return_value = paper
        response = client.get("/api/papers/10.1234%2Fspecial%20chars")
        assert response.status_code == 200
        # Verify the decoded DOI was passed to repo
        mock_repo.get_paper.assert_called_once()
