"""
Tests for agentic_kg_api.schemas -- Pydantic request/response models.

Generated by test-generator agent.
"""

import pytest
from pydantic import ValidationError

from agentic_kg_api.schemas import (
    BatchExtractRequest,
    ExtractRequest,
    GraphLink,
    GraphNode,
    GraphResponse,
    HealthResponse,
    PaperDetail,
    PaperListResponse,
    PaperSummary,
    ProblemDetail,
    ProblemListResponse,
    ProblemSummary,
    ProblemUpdate,
    SearchRequest,
    SearchResponse,
    SearchResultItem,
    StatsResponse,
)


class TestSearchRequest:
    """Tests for SearchRequest validation."""

    def test_valid_request(self):
        """Creates with valid query."""
        req = SearchRequest(query="test query")
        assert req.query == "test query"
        assert req.top_k == 10

    def test_empty_query_rejected(self):
        """Rejects empty query string."""
        with pytest.raises(ValidationError):
            SearchRequest(query="")

    def test_top_k_boundaries(self):
        """top_k must be between 1 and 100."""
        assert SearchRequest(query="test", top_k=1).top_k == 1
        assert SearchRequest(query="test", top_k=100).top_k == 100
        with pytest.raises(ValidationError):
            SearchRequest(query="test", top_k=0)
        with pytest.raises(ValidationError):
            SearchRequest(query="test", top_k=101)

    def test_semantic_weight_boundaries(self):
        """semantic_weight must be between 0.0 and 1.0."""
        assert SearchRequest(query="test", semantic_weight=0.0).semantic_weight == 0.0
        assert SearchRequest(query="test", semantic_weight=1.0).semantic_weight == 1.0
        with pytest.raises(ValidationError):
            SearchRequest(query="test", semantic_weight=-0.1)
        with pytest.raises(ValidationError):
            SearchRequest(query="test", semantic_weight=1.1)

    def test_optional_filters_default_none(self):
        """Optional filters default to None."""
        req = SearchRequest(query="test")
        assert req.domain is None
        assert req.status is None
        assert req.semantic_weight is None


class TestBatchExtractRequest:
    """Tests for BatchExtractRequest validation."""

    def test_valid_batch(self):
        """Creates with valid papers list."""
        req = BatchExtractRequest(papers=[ExtractRequest(url="https://example.com/p.pdf")])
        assert len(req.papers) == 1

    def test_empty_papers_rejected(self):
        """Rejects empty papers list."""
        with pytest.raises(ValidationError):
            BatchExtractRequest(papers=[])


class TestHealthResponse:
    """Tests for HealthResponse defaults."""

    def test_defaults(self):
        """Has sensible defaults."""
        h = HealthResponse()
        assert h.status == "ok"
        assert h.version == "0.1.0"
        assert h.neo4j_connected is False


class TestStatsResponse:
    """Tests for StatsResponse defaults."""

    def test_defaults(self):
        """Has sensible defaults."""
        s = StatsResponse()
        assert s.total_problems == 0
        assert s.total_papers == 0
        assert s.problems_by_status == {}
        assert s.problems_by_domain == {}


class TestProblemSummary:
    """Tests for ProblemSummary."""

    def test_required_fields(self):
        """Requires id, statement, and status."""
        ps = ProblemSummary(id="p1", statement="test", status="open")
        assert ps.id == "p1"
        assert ps.domain is None
        assert ps.confidence is None

    def test_missing_required_fields(self):
        """Fails without required fields."""
        with pytest.raises(ValidationError):
            ProblemSummary(id="p1")


class TestGraphResponse:
    """Tests for GraphResponse."""

    def test_empty_defaults(self):
        """Defaults to empty nodes and links."""
        g = GraphResponse()
        assert g.nodes == []
        assert g.links == []

    def test_with_data(self):
        """Accepts nodes and links."""
        g = GraphResponse(
            nodes=[GraphNode(id="n1", label="Node 1", type="problem")],
            links=[GraphLink(source="n1", target="n2", type="RELATED")],
        )
        assert len(g.nodes) == 1
        assert len(g.links) == 1
