"""
Tests for agentic_kg_api.routers.problems -- Problem CRUD endpoints.

The router serves the canonical problem read model (ProblemConcept unioned
with legacy :Problem); these tests mock the repository at the read-model
boundary (`list_problem_views` / `get_problem_view`).

Generated by test-generator agent.
"""

from datetime import datetime, timezone

import pytest
from agentic_kg.knowledge_graph.repository import NotFoundError

from tests.conftest import make_problem_view

# =============================================================================
# GET /api/problems -- List Problems
# =============================================================================


class TestListProblems:
    """Tests for GET /api/problems."""

    def test_list_problems_returns_empty_list(self, client, mock_repo):
        """Returns empty list when no problems exist."""
        mock_repo.list_problem_views.return_value = []
        response = client.get("/api/problems")
        assert response.status_code == 200
        data = response.json()
        assert data["problems"] == []
        assert data["total"] == 0
        assert data["limit"] == 50
        assert data["offset"] == 0

    def test_list_problems_returns_problems(self, client, mock_repo):
        """Returns list of problem summaries."""
        mock_repo.list_problem_views.return_value = [
            make_problem_view(id="p1", statement="Problem 1"),
            make_problem_view(id="p2", statement="Problem 2"),
        ]
        response = client.get("/api/problems")
        assert response.status_code == 200
        data = response.json()
        assert len(data["problems"]) == 2
        assert data["problems"][0]["id"] == "p1"
        assert data["problems"][1]["id"] == "p2"
        assert data["total"] == 2

    def test_list_problems_with_status_filter(self, client, mock_repo):
        """Filters problems by status."""
        mock_repo.list_problem_views.return_value = []
        response = client.get("/api/problems?status=open")
        assert response.status_code == 200
        call_kwargs = mock_repo.list_problem_views.call_args[1]
        assert call_kwargs["status"] is not None

    def test_list_problems_invalid_status_returns_400(self, client, mock_repo):
        """Invalid status value returns 400."""
        response = client.get("/api/problems?status=invalid_status_xyz")
        assert response.status_code == 400
        assert "Invalid status" in response.json()["detail"]

    def test_list_problems_with_pagination(self, client, mock_repo):
        """Supports limit and offset pagination."""
        mock_repo.list_problem_views.return_value = []
        response = client.get("/api/problems?limit=10&offset=20")
        assert response.status_code == 200
        data = response.json()
        assert data["limit"] == 10
        assert data["offset"] == 20
        call_kwargs = mock_repo.list_problem_views.call_args[1]
        assert call_kwargs["limit"] == 10
        assert call_kwargs["offset"] == 20

    @pytest.mark.parametrize("limit", [0, -1, 501])
    def test_list_problems_invalid_limit(self, client, mock_repo, limit):
        """Rejects invalid limit values."""
        response = client.get(f"/api/problems?limit={limit}")
        assert response.status_code == 422

    def test_list_problems_negative_offset(self, client, mock_repo):
        """Rejects negative offset."""
        response = client.get("/api/problems?offset=-1")
        assert response.status_code == 422

    def test_list_problems_includes_confidence(self, client, mock_repo):
        """Includes confidence from the read model when present."""
        mock_repo.list_problem_views.return_value = [
            make_problem_view(confidence=0.85)
        ]
        response = client.get("/api/problems")
        data = response.json()
        assert data["problems"][0]["confidence"] == 0.85

    def test_list_problems_carries_canonical_fields(self, client, mock_repo):
        """Concept-backed summaries expose canonical_statement + counts.

        This is the regression this fix exists for: a canonical
        ProblemConcept must be visible through /api/problems.
        """
        mock_repo.list_problem_views.return_value = [
            make_problem_view(
                id="concept-1",
                kind="concept",
                statement="Canonical: long-context efficiency",
                canonical_statement="Canonical: long-context efficiency",
                mention_count=3,
                paper_count=2,
            )
        ]
        response = client.get("/api/problems")
        assert response.status_code == 200
        problem = response.json()["problems"][0]
        assert problem["id"] == "concept-1"
        assert problem["canonical_statement"] == "Canonical: long-context efficiency"
        assert problem["mention_count"] == 3
        assert problem["paper_count"] == 2

    def test_list_problems_exposes_origin(self, client, mock_repo):
        """Agent-derived problems are labelled through the list read model."""
        mock_repo.list_problem_views.return_value = [
            make_problem_view(id="synth-1", origin="agent:synthesis"),
            make_problem_view(id="p1", origin="extracted"),
        ]
        response = client.get("/api/problems")
        assert response.status_code == 200
        origins = {p["id"]: p["origin"] for p in response.json()["problems"]}
        assert origins == {"synth-1": "agent:synthesis", "p1": "extracted"}


# =============================================================================
# GET /api/problems/{problem_id} -- Get Problem Detail
# =============================================================================


class TestGetProblem:
    """Tests for GET /api/problems/{problem_id}."""

    def test_get_existing_problem(self, client, mock_repo):
        """Returns full problem detail for existing problem."""
        mock_repo.get_problem_view.return_value = make_problem_view(
            id="p1", statement="Test problem"
        )
        response = client.get("/api/problems/p1")
        assert response.status_code == 200
        data = response.json()
        assert data["id"] == "p1"
        assert data["statement"] == "Test problem"

    def test_get_nonexistent_problem_returns_404(self, client, mock_repo):
        """Returns 404 for nonexistent problem."""
        mock_repo.get_problem_view.side_effect = NotFoundError("not found")
        response = client.get("/api/problems/nonexistent")
        assert response.status_code == 404
        assert "Problem not found" in response.json()["detail"]

    def test_get_problem_includes_evidence(self, client, mock_repo):
        """Returns evidence data when present."""
        mock_repo.get_problem_view.return_value = make_problem_view(
            evidence={
                "source_doi": "10.1234/test",
                "source_title": "Test Paper",
                "section": "Introduction",
                "quoted_text": "This is a quote.",
            }
        )
        response = client.get("/api/problems/p1")
        data = response.json()
        assert data["evidence"]["source_doi"] == "10.1234/test"

    def test_get_problem_includes_extraction_metadata(self, client, mock_repo):
        """Returns extraction metadata when present."""
        mock_repo.get_problem_view.return_value = make_problem_view(
            extraction_metadata={
                "extraction_model": "gpt-4",
                "confidence_score": 0.9,
                "extractor_version": "1.0",
                "human_reviewed": False,
            }
        )
        response = client.get("/api/problems/p1")
        data = response.json()
        assert data["extraction_metadata"]["extraction_model"] == "gpt-4"
        assert data["extraction_metadata"]["confidence_score"] == 0.9

    def test_get_problem_includes_assumptions(self, client, mock_repo):
        """Returns assumptions list."""
        mock_repo.get_problem_view.return_value = make_problem_view(
            assumptions=[{"text": "Data is IID", "implicit": False, "confidence": 0.8}]
        )
        response = client.get("/api/problems/p1")
        data = response.json()
        assert len(data["assumptions"]) == 1
        assert data["assumptions"][0]["text"] == "Data is IID"

    def test_get_problem_exposes_origin(self, client, mock_repo):
        """Agent-derived problems are labelled on the detail response."""
        mock_repo.get_problem_view.return_value = make_problem_view(
            id="synth-1", origin="agent:synthesis"
        )
        response = client.get("/api/problems/synth-1")
        assert response.status_code == 200
        assert response.json()["origin"] == "agent:synthesis"

    def test_get_concept_detail_includes_mentions_and_evidence(
        self, client, mock_repo
    ):
        """A ProblemConcept detail carries its mentions / evidence / papers."""
        created = datetime(2026, 1, 1, tzinfo=timezone.utc)
        mock_repo.get_problem_view.return_value = make_problem_view(
            id="concept-1",
            kind="concept",
            statement="Canonical problem statement here",
            canonical_statement="Canonical problem statement here",
            mention_count=1,
            paper_count=1,
            evidence={
                "source_doi": "10.1234/paper",
                "source_title": "A Paper",
                "section": "Introduction",
                "quoted_text": "we could not scale it",
            },
            mentions=[
                {
                    "id": "mention-1",
                    "statement": "we could not scale it",
                    "quoted_text": "we could not scale it",
                    "section": "Introduction",
                    "paper_doi": "10.1234/paper",
                    "paper_title": "A Paper",
                    "paper_year": 2024,
                    "confidence": 0.97,
                    "match_confidence": "high",
                    "review_status": "approved",
                    "created_at": created,
                }
            ],
            papers=[{"doi": "10.1234/paper", "title": "A Paper", "year": 2024}],
        )
        response = client.get("/api/problems/concept-1")
        assert response.status_code == 200
        data = response.json()
        assert data["canonical_statement"] == "Canonical problem statement here"
        assert data["mention_count"] == 1
        assert data["paper_count"] == 1
        assert len(data["mentions"]) == 1
        assert data["mentions"][0]["paper_doi"] == "10.1234/paper"
        assert data["papers"][0]["doi"] == "10.1234/paper"
        assert data["evidence"]["quoted_text"] == "we could not scale it"


# =============================================================================
# PUT /api/problems/{problem_id} -- Update Problem
# =============================================================================


class TestUpdateProblem:
    """Tests for PUT /api/problems/{problem_id}."""

    def test_update_status(self, client, mock_repo):
        """Updates a legacy problem's status."""
        mock_repo.get_problem_view.return_value = make_problem_view(
            id="p1", kind="problem"
        )
        mock_repo.update_problem.return_value = None
        response = client.put("/api/problems/p1", json={"status": "open"})
        assert response.status_code == 200
        mock_repo.update_problem.assert_called_once()

    def test_update_statement(self, client, mock_repo):
        """Updates a legacy problem's statement."""
        mock_repo.get_problem_view.return_value = make_problem_view(
            id="p1", kind="problem"
        )
        mock_repo.update_problem.return_value = None
        response = client.put("/api/problems/p1", json={"statement": "Updated"})
        assert response.status_code == 200

    def test_update_concept_routes_to_concept_writer(self, client, mock_repo):
        """A canonical ProblemConcept update uses the concept writer."""
        mock_repo.get_problem_view.return_value = make_problem_view(
            id="concept-1", kind="concept"
        )
        mock_repo.update_problem_concept.return_value = make_problem_view(
            id="concept-1", kind="concept", status="in_progress"
        )
        response = client.put(
            "/api/problems/concept-1", json={"status": "in_progress"}
        )
        assert response.status_code == 200
        assert response.json()["status"] == "in_progress"
        mock_repo.update_problem_concept.assert_called_once()
        mock_repo.update_problem.assert_not_called()

    def test_update_nonexistent_problem_returns_404(self, client, mock_repo):
        """Returns 404 when updating nonexistent problem."""
        mock_repo.get_problem_view.side_effect = NotFoundError("not found")
        response = client.put("/api/problems/nonexistent", json={"status": "open"})
        assert response.status_code == 404

    def test_update_invalid_status_returns_400(self, client, mock_repo):
        """Returns 400 for invalid status value."""
        mock_repo.get_problem_view.return_value = make_problem_view(id="p1")
        response = client.put("/api/problems/p1", json={"status": "bogus_status"})
        assert response.status_code == 400
        assert "Invalid status" in response.json()["detail"]


# =============================================================================
# DELETE /api/problems/{problem_id} -- Delete Problem
# =============================================================================


class TestDeleteProblem:
    """Tests for DELETE /api/problems/{problem_id}."""

    def test_delete_existing_problem(self, client, mock_repo):
        """Soft-deletes an existing problem."""
        response = client.delete("/api/problems/p1")
        assert response.status_code == 200
        data = response.json()
        assert data["deleted"] is True
        assert data["id"] == "p1"
        mock_repo.delete_problem.assert_called_once_with("p1", soft=True)

    def test_delete_nonexistent_problem_returns_404(self, client, mock_repo):
        """Returns 404 when deleting nonexistent problem."""
        mock_repo.delete_problem.side_effect = NotFoundError("not found")
        response = client.delete("/api/problems/nonexistent")
        assert response.status_code == 404
