"""
Tests for agentic_kg_api.routers.search -- Hybrid search endpoint.

Generated by test-generator agent.
"""

import pytest
from unittest.mock import MagicMock

from tests.conftest import make_problem, make_search_result


# =============================================================================
# POST /api/search -- Hybrid Search
# =============================================================================


class TestSearchProblems:
    """Tests for POST /api/search."""

    def test_search_returns_results(self, client, mock_search_service):
        """Search returns matching problems."""
        mock_search_service.hybrid_search.return_value = [
            make_search_result(problem=make_problem(id="p1"), score=0.95, match_type="semantic"),
            make_search_result(problem=make_problem(id="p2"), score=0.80, match_type="structured"),
        ]
        response = client.post("/api/search", json={"query": "transformer efficiency"})
        assert response.status_code == 200
        data = response.json()
        assert data["query"] == "transformer efficiency"
        assert data["total"] == 2
        assert len(data["results"]) == 2
        assert data["results"][0]["score"] == 0.95
        assert data["results"][0]["match_type"] == "semantic"

    def test_search_empty_results(self, client, mock_search_service):
        """Search returns empty list when no matches."""
        mock_search_service.hybrid_search.return_value = []
        response = client.post("/api/search", json={"query": "nonexistent topic"})
        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 0
        assert data["results"] == []

    def test_search_with_filters(self, client, mock_search_service):
        """Search passes domain and status filters."""
        mock_search_service.hybrid_search.return_value = []
        response = client.post("/api/search", json={
            "query": "test",
            "domain": "NLP",
            "status": "open",
            "top_k": 5,
            "semantic_weight": 0.7,
        })
        assert response.status_code == 200
        call_kwargs = mock_search_service.hybrid_search.call_args[1]
        assert call_kwargs["domain"] == "NLP"
        assert call_kwargs["top_k"] == 5
        assert call_kwargs["semantic_weight"] == 0.7

    def test_search_empty_query_rejected(self, client, mock_search_service):
        """Empty query string is rejected (min_length=1)."""
        response = client.post("/api/search", json={"query": ""})
        assert response.status_code == 422

    def test_search_missing_query_rejected(self, client, mock_search_service):
        """Missing query field is rejected."""
        response = client.post("/api/search", json={})
        assert response.status_code == 422

    @pytest.mark.parametrize("top_k", [0, -1, 101])
    def test_search_invalid_top_k(self, client, mock_search_service, top_k):
        """Rejects top_k outside valid range [1, 100]."""
        response = client.post("/api/search", json={"query": "test", "top_k": top_k})
        assert response.status_code == 422

    @pytest.mark.parametrize("weight", [-0.1, 1.1])
    def test_search_invalid_semantic_weight(self, client, mock_search_service, weight):
        """Rejects semantic_weight outside [0.0, 1.0]."""
        response = client.post("/api/search", json={"query": "test", "semantic_weight": weight})
        assert response.status_code == 422

    def test_search_invalid_status_is_ignored(self, client, mock_search_service):
        """Invalid status is silently ignored (not an error)."""
        mock_search_service.hybrid_search.return_value = []
        response = client.post("/api/search", json={"query": "test", "status": "bogus"})
        assert response.status_code == 200
        call_kwargs = mock_search_service.hybrid_search.call_args[1]
        assert call_kwargs["status"] is None

    def test_search_result_includes_confidence(self, client, mock_search_service):
        """Search results include confidence from extraction metadata."""
        meta = MagicMock()
        meta.confidence_score = 0.88
        problem = make_problem(extraction_metadata=meta)
        mock_search_service.hybrid_search.return_value = [
            make_search_result(problem=problem),
        ]
        response = client.post("/api/search", json={"query": "test"})
        data = response.json()
        assert data["results"][0]["problem"]["confidence"] == 0.88
