"""
Tests for agentic_kg_api.routers.graph -- Graph data endpoints.

Generated by test-generator agent.
"""

import pytest
from unittest.mock import MagicMock, patch


def _make_neo4j_node(element_id, properties, labels=None):
    """Create a mock Neo4j node."""
    node = MagicMock()
    node.element_id = element_id
    node.get = lambda key, default=None: properties.get(key, default)
    node.labels = labels or set()
    node.__getitem__ = lambda self, key: properties[key]
    return node


# =============================================================================
# GET /api/graph -- Get Graph Data
# =============================================================================


class TestGetGraph:
    """Tests for GET /api/graph."""

    @patch("agentic_kg_api.routers.graph.get_repo")
    def test_get_graph_empty(self, mock_get_repo, client):
        """Returns empty graph when no data."""
        mock_repo = MagicMock()
        mock_session = MagicMock()
        mock_result = MagicMock()
        mock_result.__iter__ = MagicMock(return_value=iter([]))
        mock_session.run.return_value = mock_result
        mock_repo.session.return_value.__enter__ = MagicMock(return_value=mock_session)
        mock_repo.session.return_value.__exit__ = MagicMock(return_value=False)
        mock_get_repo.return_value = mock_repo

        response = client.get("/api/graph")
        assert response.status_code == 200
        data = response.json()
        assert data["nodes"] == []
        assert data["links"] == []

    @patch("agentic_kg_api.routers.graph.get_repo")
    def test_get_graph_with_problems(self, mock_get_repo, client):
        """Returns problem nodes."""
        mock_repo = MagicMock()
        mock_session = MagicMock()

        problem_node = _make_neo4j_node("elem1", {
            "statement": "How to scale transformers?",
            "domain": "NLP",
            "status": "open",
            "confidence": 0.9,
        })

        # First call: problem nodes
        problems_result = MagicMock()
        problems_result.__iter__ = MagicMock(return_value=iter([{"p": problem_node}]))

        # Subsequent calls: relations, papers -- all empty
        empty_result = MagicMock()
        empty_result.__iter__ = MagicMock(return_value=iter([]))

        mock_session.run.side_effect = [problems_result, empty_result, empty_result]
        mock_repo.session.return_value.__enter__ = MagicMock(return_value=mock_session)
        mock_repo.session.return_value.__exit__ = MagicMock(return_value=False)
        mock_get_repo.return_value = mock_repo

        response = client.get("/api/graph")
        assert response.status_code == 200
        data = response.json()
        # Should have problem node + domain node
        problem_nodes = [n for n in data["nodes"] if n["type"] == "problem"]
        assert len(problem_nodes) >= 1
        assert problem_nodes[0]["properties"]["domain"] == "NLP"

    @patch("agentic_kg_api.routers.graph.get_repo")
    def test_get_graph_handles_error(self, mock_get_repo, client):
        """Returns empty graph on database error."""
        mock_get_repo.side_effect = Exception("db error")
        response = client.get("/api/graph")
        assert response.status_code == 200
        data = response.json()
        assert data["nodes"] == []
        assert data["links"] == []

    def test_get_graph_with_domain_filter(self, client):
        """Accepts domain query parameter."""
        with patch("agentic_kg_api.routers.graph.get_repo", side_effect=Exception("skip")):
            response = client.get("/api/graph?domain=NLP")
        assert response.status_code == 200

    @pytest.mark.parametrize("limit", [0, -1, 501])
    def test_get_graph_invalid_limit(self, client, limit):
        """Rejects invalid limit values."""
        response = client.get(f"/api/graph?limit={limit}")
        assert response.status_code == 422


# =============================================================================
# GET /api/graph/neighbors/{node_id} -- Get Neighbors
# =============================================================================


class TestGetNeighbors:
    """Tests for GET /api/graph/neighbors/{node_id}."""

    @patch("agentic_kg_api.routers.graph.get_repo")
    def test_get_neighbors_empty(self, mock_get_repo, client):
        """Returns empty graph when no neighbors found."""
        mock_repo = MagicMock()
        mock_session = MagicMock()
        mock_result = MagicMock()
        mock_result.single.return_value = None
        mock_session.run.return_value = mock_result
        mock_repo.session.return_value.__enter__ = MagicMock(return_value=mock_session)
        mock_repo.session.return_value.__exit__ = MagicMock(return_value=False)
        mock_get_repo.return_value = mock_repo

        response = client.get("/api/graph/neighbors/problem:elem1")
        assert response.status_code == 200
        data = response.json()
        assert data["nodes"] == []

    @patch("agentic_kg_api.routers.graph.get_repo")
    def test_get_neighbors_handles_error(self, mock_get_repo, client):
        """Returns empty graph on error."""
        mock_get_repo.side_effect = Exception("db error")
        response = client.get("/api/graph/neighbors/problem:elem1")
        assert response.status_code == 200
        data = response.json()
        assert data["nodes"] == []

    @pytest.mark.parametrize("depth", [0, -1, 4])
    def test_get_neighbors_invalid_depth(self, client, depth):
        """Rejects depth outside [1, 3]."""
        response = client.get(f"/api/graph/neighbors/problem:elem1?depth={depth}")
        assert response.status_code == 422
