"""
Tests for agentic_kg_api.routers.extract -- Extraction trigger endpoints.

Generated by test-generator agent.
"""

import pytest
from unittest.mock import AsyncMock, MagicMock, patch


def _make_pipeline_result(success=True, title="Test Paper", problem_count=2, relation_count=1):
    """Create a mock PaperProcessingResult."""
    result = MagicMock()
    result.success = success
    result.paper_title = title
    result.problem_count = problem_count
    result.relation_count = relation_count
    result.total_duration_ms = 1234.5

    # Mock extracted problems
    p1 = MagicMock()
    p1.statement = "Problem 1"
    p1.domain = "NLP"
    p1.confidence = 0.9
    p1.quoted_text = "Some quoted text from the paper"
    p2 = MagicMock()
    p2.statement = "Problem 2"
    p2.domain = "CV"
    p2.confidence = 0.7
    p2.quoted_text = "Another quote"
    result.get_problems.return_value = [p1, p2] if success else []

    # Mock stages
    stage = MagicMock()
    stage.stage = "extract"
    stage.success = True
    stage.duration_ms = 500.0
    stage.error = None
    result.stages = [stage]

    return result


# =============================================================================
# POST /api/extract -- Single Extraction
# =============================================================================


class TestExtract:
    """Tests for POST /api/extract."""

    @patch("agentic_kg_api.routers.extract.get_pipeline")
    def test_extract_from_url(self, mock_get_pipeline, client):
        """Extracts problems from a PDF URL."""
        mock_pipeline = MagicMock()
        mock_pipeline.process_pdf_url = AsyncMock(return_value=_make_pipeline_result())
        mock_get_pipeline.return_value = mock_pipeline

        response = client.post("/api/extract", json={
            "url": "https://arxiv.org/pdf/2401.00001",
            "title": "Test Paper",
            "doi": "10.1234/test",
            "authors": ["Author A"],
        })
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        assert data["paper_title"] == "Test Paper"
        assert data["problems_extracted"] == 2
        assert len(data["problems"]) == 2
        assert data["problems"][0]["statement"] == "Problem 1"

    @patch("agentic_kg_api.routers.extract.get_pipeline")
    def test_extract_from_text(self, mock_get_pipeline, client):
        """Extracts problems from raw text."""
        mock_pipeline = MagicMock()
        mock_pipeline.process_text = AsyncMock(return_value=_make_pipeline_result())
        mock_get_pipeline.return_value = mock_pipeline

        response = client.post("/api/extract", json={
            "text": "This paper addresses the problem of...",
            "title": "Text Input Paper",
        })
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True

    def test_extract_no_url_or_text_returns_400(self, client):
        """Returns 400 when neither url nor text is provided."""
        response = client.post("/api/extract", json={})
        assert response.status_code == 400
        assert "Must provide either" in response.json()["detail"]

    @patch("agentic_kg_api.routers.extract.get_pipeline")
    def test_extract_includes_stages(self, mock_get_pipeline, client):
        """Response includes pipeline stage information."""
        mock_pipeline = MagicMock()
        mock_pipeline.process_pdf_url = AsyncMock(return_value=_make_pipeline_result())
        mock_get_pipeline.return_value = mock_pipeline

        response = client.post("/api/extract", json={"url": "https://example.com/paper.pdf"})
        data = response.json()
        assert len(data["stages"]) == 1
        assert data["stages"][0]["stage"] == "extract"
        assert data["stages"][0]["success"] is True

    @patch("agentic_kg_api.routers.extract.get_pipeline")
    def test_extract_text_uses_default_title(self, mock_get_pipeline, client):
        """Text extraction uses default title when none provided."""
        mock_pipeline = MagicMock()
        mock_pipeline.process_text = AsyncMock(return_value=_make_pipeline_result())
        mock_get_pipeline.return_value = mock_pipeline

        response = client.post("/api/extract", json={"text": "Some text"})
        assert response.status_code == 200
        call_kwargs = mock_pipeline.process_text.call_args[1]
        assert call_kwargs["paper_title"] == "Direct text input"


# =============================================================================
# POST /api/extract/batch -- Batch Extraction
# =============================================================================


class TestExtractBatch:
    """Tests for POST /api/extract/batch."""

    @patch("agentic_kg_api.routers.extract.get_pipeline")
    def test_batch_extract_multiple(self, mock_get_pipeline, client):
        """Processes multiple papers in batch."""
        mock_pipeline = MagicMock()
        mock_pipeline.process_pdf_url = AsyncMock(return_value=_make_pipeline_result())
        mock_pipeline.process_text = AsyncMock(return_value=_make_pipeline_result(title="Text Paper"))
        mock_get_pipeline.return_value = mock_pipeline

        response = client.post("/api/extract/batch", json={
            "papers": [
                {"url": "https://example.com/paper1.pdf", "title": "Paper 1"},
                {"text": "Some text content", "title": "Paper 2"},
            ]
        })
        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 2
        assert data["succeeded"] == 2
        assert data["failed"] == 0
        assert data["total_problems"] == 4  # 2 per paper

    @patch("agentic_kg_api.routers.extract.get_pipeline")
    def test_batch_extract_with_failures(self, mock_get_pipeline, client):
        """Handles individual paper failures in batch."""
        mock_pipeline = MagicMock()
        mock_pipeline.process_pdf_url = AsyncMock(side_effect=Exception("Download failed"))
        mock_get_pipeline.return_value = mock_pipeline

        response = client.post("/api/extract/batch", json={
            "papers": [
                {"url": "https://example.com/bad.pdf", "title": "Bad Paper"},
            ]
        })
        assert response.status_code == 200
        data = response.json()
        assert data["succeeded"] == 0
        assert data["failed"] == 1
        assert data["results"][0]["success"] is False

    def test_batch_extract_empty_papers_rejected(self, client):
        """Rejects batch request with empty papers list."""
        response = client.post("/api/extract/batch", json={"papers": []})
        assert response.status_code == 422

    @patch("agentic_kg_api.routers.extract.get_pipeline")
    def test_batch_skips_papers_without_url_or_text(self, mock_get_pipeline, client):
        """Papers with neither url nor text are skipped."""
        mock_pipeline = MagicMock()
        mock_get_pipeline.return_value = mock_pipeline

        response = client.post("/api/extract/batch", json={
            "papers": [
                {"title": "No content paper"},
            ]
        })
        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 0
