"""
Tests for agentic_kg_api.routers.graph -- Graph data endpoints.

Generated by test-generator agent.
"""

from unittest.mock import MagicMock

import pytest


def _make_neo4j_node(element_id, properties, labels=None):
    """Create a mock Neo4j node."""
    node = MagicMock()
    node.element_id = element_id
    node.get = lambda key, default=None: properties.get(key, default)
    node.labels = labels or set()
    node.__getitem__ = lambda self, key: properties[key]
    return node


def _wire_session(mock_repo, session):
    mock_repo.session.return_value.__enter__ = MagicMock(return_value=session)
    mock_repo.session.return_value.__exit__ = MagicMock(return_value=False)


def _empty_result():
    result = MagicMock()
    result.__iter__ = MagicMock(return_value=iter([]))
    return result


# =============================================================================
# GET /api/graph -- Get Graph Data
# =============================================================================


class TestGetGraph:
    """Tests for GET /api/graph."""

    def test_get_graph_empty(self, client, mock_repo):
        """Returns empty graph when no data."""
        session = MagicMock()
        session.run.return_value = _empty_result()
        _wire_session(mock_repo, session)

        response = client.get("/api/graph")
        assert response.status_code == 200
        data = response.json()
        assert data["nodes"] == []
        assert data["links"] == []

    def test_get_graph_with_problems(self, client, mock_repo):
        """Returns canonical problem (ProblemConcept) nodes."""
        session = MagicMock()

        problem_node = _make_neo4j_node("elem1", {
            "canonical_statement": "How to scale transformers?",
            "status": "open",
            "confidence": 0.9,
        })

        # First call: concept scan. Every subsequent call (legacy problems,
        # relations, papers, topics) returns empty.
        problems_result = MagicMock()
        problems_result.__iter__ = MagicMock(return_value=iter([{"c": problem_node}]))

        empty_result = _empty_result()
        calls = {"n": 0}

        def _run(*args, **kwargs):
            calls["n"] += 1
            return problems_result if calls["n"] == 1 else empty_result

        session.run.side_effect = _run
        _wire_session(mock_repo, session)

        response = client.get("/api/graph")
        assert response.status_code == 200
        data = response.json()
        problem_nodes = [n for n in data["nodes"] if n["type"] == "problem"]
        assert len(problem_nodes) >= 1
        assert problem_nodes[0]["properties"]["status"] == "open"

    def test_get_graph_handles_error(self, client, mock_repo):
        """Returns empty graph on database error."""
        mock_repo.session.side_effect = Exception("db error")
        response = client.get("/api/graph")
        assert response.status_code == 200
        data = response.json()
        assert data["nodes"] == []
        assert data["links"] == []

    def test_get_graph_with_topic_filter(self, client, mock_repo):
        """Accepts topic_id query parameter."""
        session = MagicMock()
        session.run.return_value = _empty_result()
        _wire_session(mock_repo, session)
        response = client.get("/api/graph?topic_id=topic-uuid-1")
        assert response.status_code == 200

    @pytest.mark.parametrize("limit", [0, -1, 501])
    def test_get_graph_invalid_limit(self, client, mock_repo, limit):
        """Rejects invalid limit values."""
        response = client.get(f"/api/graph?limit={limit}")
        assert response.status_code == 422


# =============================================================================
# GET /api/graph/neighbors/{node_id} -- Get Neighbors
# =============================================================================


class TestGetNeighbors:
    """Tests for GET /api/graph/neighbors/{node_id}."""

    def test_get_neighbors_empty(self, client, mock_repo):
        """Returns empty graph when no neighbors found."""
        session = MagicMock()
        result = MagicMock()
        result.single.return_value = None
        session.run.return_value = result
        _wire_session(mock_repo, session)

        response = client.get("/api/graph/neighbors/problem:elem1")
        assert response.status_code == 200
        data = response.json()
        assert data["nodes"] == []

    def test_get_neighbors_handles_error(self, client, mock_repo):
        """Returns empty graph on error."""
        mock_repo.session.side_effect = Exception("db error")
        response = client.get("/api/graph/neighbors/problem:elem1")
        assert response.status_code == 200
        data = response.json()
        assert data["nodes"] == []

    @pytest.mark.parametrize("depth", [0, -1, 4])
    def test_get_neighbors_invalid_depth(self, client, mock_repo, depth):
        """Rejects depth outside [1, 3]."""
        response = client.get(f"/api/graph/neighbors/problem:elem1?depth={depth}")
        assert response.status_code == 422
