"""
Knowledge Graph synchronization for paper acquisition.

Provides functions to sync acquired papers to the Neo4j Knowledge Graph:
- Map PaperMetadata to KG Paper entity
- Map AuthorRef to KG Author entity
- Create AUTHORED_BY relations
- Handle duplicate detection and updates
"""

import logging
from datetime import datetime
from typing import Optional

from agentic_kg.data_acquisition.models import AuthorRef, PaperMetadata
from agentic_kg.knowledge_graph.models import Author, Paper
from agentic_kg.knowledge_graph.repository import (
    DuplicateError,
    Neo4jRepository,
    NotFoundError,
    get_repository,
)
from agentic_kg.knowledge_graph.relations import RelationService

logger = logging.getLogger(__name__)


class KGSyncError(Exception):
    """Error during Knowledge Graph synchronization."""

    pass


class KGSyncResult:
    """Result of a KG synchronization operation."""

    def __init__(self):
        self.papers_created: int = 0
        self.papers_updated: int = 0
        self.papers_skipped: int = 0
        self.authors_created: int = 0
        self.authors_updated: int = 0
        self.relations_created: int = 0
        self.errors: list[str] = []

    @property
    def success(self) -> bool:
        """Check if sync was successful (no errors)."""
        return len(self.errors) == 0

    def __repr__(self) -> str:
        return (
            f"KGSyncResult(papers_created={self.papers_created}, "
            f"papers_updated={self.papers_updated}, "
            f"authors_created={self.authors_created}, "
            f"relations_created={self.relations_created}, "
            f"errors={len(self.errors)})"
        )


def paper_metadata_to_kg_paper(metadata: PaperMetadata) -> Paper:
    """
    Convert PaperMetadata from acquisition to KG Paper entity.

    Args:
        metadata: Paper metadata from acquisition layer

    Returns:
        KG Paper entity

    Raises:
        ValueError: If DOI is missing
    """
    if not metadata.doi:
        raise ValueError("Paper must have DOI for Knowledge Graph sync")

    # Get author names
    author_names = [author.name for author in metadata.authors]

    return Paper(
        doi=metadata.doi,
        title=metadata.title,
        authors=author_names,
        venue=metadata.venue,
        year=metadata.year or datetime.utcnow().year,
        abstract=metadata.abstract,
        arxiv_id=metadata.arxiv_id,
        openalex_id=metadata.openalex_id,
        semantic_scholar_id=metadata.s2_id,
        pdf_url=metadata.pdf_url,
        ingested_at=metadata.retrieved_at,
    )


def author_ref_to_kg_author(
    author_ref: AuthorRef,
    existing_id: Optional[str] = None,
) -> Author:
    """
    Convert AuthorRef from acquisition to KG Author entity.

    Args:
        author_ref: Author reference from acquisition layer
        existing_id: Use existing author ID if updating

    Returns:
        KG Author entity
    """
    # Generate stable ID from author info if not provided
    author_id = existing_id
    if not author_id:
        # Try to use semantic scholar ID as stable identifier
        if author_ref.author_id:
            author_id = f"s2:{author_ref.author_id}"
        elif author_ref.orcid:
            author_id = f"orcid:{author_ref.orcid}"
        # Otherwise, a UUID will be generated by the model

    kwargs = {
        "name": author_ref.name,
        "affiliations": author_ref.affiliations,
        "orcid": author_ref.orcid,
        "semantic_scholar_id": author_ref.author_id,
    }

    if author_id:
        kwargs["id"] = author_id

    return Author(**kwargs)


def find_existing_author(
    repository: Neo4jRepository,
    author_ref: AuthorRef,
) -> Optional[Author]:
    """
    Try to find an existing author in the KG.

    Looks up by:
    1. Semantic Scholar ID
    2. ORCID
    3. Name match (as fallback)

    Args:
        repository: Neo4j repository
        author_ref: Author reference to find

    Returns:
        Existing Author if found, None otherwise
    """
    # Try by Semantic Scholar ID
    if author_ref.author_id:
        author_id = f"s2:{author_ref.author_id}"
        try:
            return repository.get_author(author_id)
        except NotFoundError:
            pass

    # Try by ORCID
    if author_ref.orcid:
        author_id = f"orcid:{author_ref.orcid}"
        try:
            return repository.get_author(author_id)
        except NotFoundError:
            pass

    # Name-based lookup would require index/search, skip for now
    return None


def sync_paper_to_kg(
    metadata: PaperMetadata,
    repository: Optional[Neo4jRepository] = None,
    update_existing: bool = True,
    sync_authors: bool = True,
) -> KGSyncResult:
    """
    Sync a paper to the Knowledge Graph.

    Args:
        metadata: Paper metadata from acquisition layer
        repository: Neo4j repository (uses singleton if not provided)
        update_existing: Update existing papers with new metadata
        sync_authors: Also sync authors and create relations

    Returns:
        Sync result with counts and errors
    """
    result = KGSyncResult()
    repo = repository or get_repository()

    # Must have DOI for sync
    if not metadata.doi:
        result.errors.append("Paper missing DOI, cannot sync to KG")
        result.papers_skipped += 1
        return result

    # Convert to KG Paper
    try:
        kg_paper = paper_metadata_to_kg_paper(metadata)
    except ValueError as e:
        result.errors.append(f"Failed to convert paper: {e}")
        result.papers_skipped += 1
        return result

    # Try to create or update paper
    try:
        repo.create_paper(kg_paper)
        result.papers_created += 1
        logger.info(f"Created paper in KG: {kg_paper.doi}")
    except DuplicateError:
        if update_existing:
            try:
                repo.update_paper(kg_paper)
                result.papers_updated += 1
                logger.info(f"Updated paper in KG: {kg_paper.doi}")
            except NotFoundError:
                result.errors.append(f"Paper disappeared during update: {kg_paper.doi}")
        else:
            result.papers_skipped += 1
            logger.debug(f"Skipped existing paper: {kg_paper.doi}")

    # Sync authors if requested
    if sync_authors and metadata.authors:
        author_result = _sync_authors_for_paper(
            metadata.doi,
            metadata.authors,
            repo,
        )
        result.authors_created += author_result.authors_created
        result.authors_updated += author_result.authors_updated
        result.relations_created += author_result.relations_created
        result.errors.extend(author_result.errors)

    return result


def _sync_authors_for_paper(
    paper_doi: str,
    authors: list[AuthorRef],
    repository: Neo4jRepository,
) -> KGSyncResult:
    """
    Sync authors for a paper and create AUTHORED_BY relations.

    Args:
        paper_doi: Paper DOI
        authors: List of author references
        repository: Neo4j repository

    Returns:
        Sync result for authors
    """
    result = KGSyncResult()
    relation_repo = RelationService(repository)

    for position, author_ref in enumerate(authors, start=1):
        # Try to find existing author
        existing = find_existing_author(repository, author_ref)

        if existing:
            # Update existing author with new info
            kg_author = author_ref_to_kg_author(author_ref, existing.id)
            kg_author.id = existing.id
            try:
                repository.update_author(kg_author)
                result.authors_updated += 1
            except NotFoundError:
                pass  # Race condition, ignore
        else:
            # Create new author
            kg_author = author_ref_to_kg_author(author_ref)
            try:
                repository.create_author(kg_author)
                result.authors_created += 1
                logger.debug(f"Created author: {kg_author.name}")
            except DuplicateError:
                # Author was created by another process
                result.authors_updated += 1

        # Create AUTHORED_BY relation
        try:
            relation_repo.create_authored_by_relation(
                paper_doi=paper_doi,
                author_id=kg_author.id,
                author_position=position,
            )
            result.relations_created += 1
        except NotFoundError as e:
            result.errors.append(f"Failed to link author {kg_author.name}: {e}")
        except Exception as e:
            result.errors.append(f"Error creating relation for {kg_author.name}: {e}")

    return result


def sync_papers_batch(
    papers: list[PaperMetadata],
    repository: Optional[Neo4jRepository] = None,
    update_existing: bool = True,
    sync_authors: bool = True,
) -> KGSyncResult:
    """
    Sync multiple papers to the Knowledge Graph.

    Args:
        papers: List of paper metadata
        repository: Neo4j repository
        update_existing: Update existing papers
        sync_authors: Also sync authors

    Returns:
        Combined sync result
    """
    result = KGSyncResult()
    repo = repository or get_repository()

    for metadata in papers:
        paper_result = sync_paper_to_kg(
            metadata,
            repo,
            update_existing,
            sync_authors,
        )
        result.papers_created += paper_result.papers_created
        result.papers_updated += paper_result.papers_updated
        result.papers_skipped += paper_result.papers_skipped
        result.authors_created += paper_result.authors_created
        result.authors_updated += paper_result.authors_updated
        result.relations_created += paper_result.relations_created
        result.errors.extend(paper_result.errors)

    logger.info(
        f"Batch sync complete: {result.papers_created} created, "
        f"{result.papers_updated} updated, {len(result.errors)} errors"
    )

    return result


def get_paper_from_kg(doi: str, repository: Optional[Neo4jRepository] = None) -> Optional[Paper]:
    """
    Get a paper from the Knowledge Graph by DOI.

    Args:
        doi: Paper DOI
        repository: Neo4j repository

    Returns:
        Paper if found, None otherwise
    """
    repo = repository or get_repository()
    try:
        return repo.get_paper(doi)
    except NotFoundError:
        return None


def paper_exists_in_kg(doi: str, repository: Optional[Neo4jRepository] = None) -> bool:
    """
    Check if a paper exists in the Knowledge Graph.

    Args:
        doi: Paper DOI
        repository: Neo4j repository

    Returns:
        True if paper exists
    """
    return get_paper_from_kg(doi, repository) is not None
