"""
Tests for agentic_kg.agents.ranking.

Generated by test-generator agent.
"""

from types import SimpleNamespace
from unittest.mock import AsyncMock, MagicMock

import pytest

from agentic_kg.agents.ranking import RankingAgent
from agentic_kg.agents.schemas import RankedProblem, RankingResult, WorkflowStatus
from agentic_kg.agents.state import create_initial_state


# =============================================================================
# Tests
# =============================================================================


class TestRankingAgent:
    """Tests for RankingAgent."""

    @pytest.fixture
    def agent(self, mock_llm, mock_repo, mock_search, mock_relations):
        """Create a RankingAgent with mocked dependencies."""
        return RankingAgent(
            llm_client=mock_llm,
            repository=mock_repo,
            search_service=mock_search,
            relation_service=mock_relations,
        )

    @pytest.fixture
    def ranking_result(self):
        """A mock RankingResult from the LLM."""
        return RankingResult(
            ranked_problems=[
                RankedProblem(
                    problem_id="prob-1",
                    statement="How to improve GNN scalability?",
                    score=0.85,
                    tractability=0.8,
                    data_availability=0.9,
                    cross_domain_impact=0.7,
                    rationale="High tractability with available data.",
                ),
            ],
            query_summary="Filtered by graph_ml domain",
            total_candidates=5,
        )

    def test_name(self, agent):
        """Agent name is 'ranking'."""
        assert agent.name == "ranking"

    @pytest.mark.asyncio
    async def test_run_happy_path(self, agent, mock_llm, ranking_result, initial_state):
        """Run returns ranked problems from LLM."""
        mock_llm.structured_extract.return_value = SimpleNamespace(content=ranking_result)

        result = await agent.run(initial_state)

        assert result["current_step"] == "ranking"
        assert len(result["ranked_problems"]) == 1
        assert result["ranked_problems"][0]["problem_id"] == "prob-1"
        assert result["total_candidates"] == 5
        mock_llm.structured_extract.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_run_no_candidates(self, agent, mock_search, initial_state):
        """Run with no candidates returns empty list."""
        mock_search.structured_search.return_value = []

        result = await agent.run(initial_state)

        assert result["ranked_problems"] == []
        assert result["total_candidates"] == 0

    @pytest.mark.asyncio
    async def test_run_uses_repo_when_no_search(self, mock_llm, mock_repo, mock_relations):
        """Falls back to repo.list_problems when search_service is None."""
        agent = RankingAgent(
            llm_client=mock_llm,
            repository=mock_repo,
            search_service=None,
            relation_service=mock_relations,
        )
        ranking_result = RankingResult(
            ranked_problems=[],
            total_candidates=1,
        )
        mock_llm.structured_extract.return_value = SimpleNamespace(content=ranking_result)

        state = create_initial_state()
        result = await agent.run(state)

        mock_repo.list_problems.assert_called_once()

    @pytest.mark.asyncio
    async def test_run_handles_llm_error(self, agent, mock_llm, mock_search, initial_state):
        """Run handles LLM errors gracefully."""
        mock_llm.structured_extract.side_effect = RuntimeError("LLM down")

        result = await agent.run(initial_state)

        assert "LLM down" in result["errors"][-1]

    @pytest.mark.asyncio
    async def test_run_with_domain_filter(self, agent, mock_search, mock_llm, ranking_result):
        """Domain filter is passed to search service."""
        mock_llm.structured_extract.return_value = SimpleNamespace(content=ranking_result)
        state = create_initial_state(domain_filter="physics")

        await agent.run(state)

        call_kwargs = mock_search.structured_search.call_args
        assert call_kwargs.kwargs.get("domain") == "physics" or \
               (call_kwargs.args and "physics" in str(call_kwargs))

    def test_format_problems(self, agent):
        """_format_problems produces numbered text."""
        candidates = [
            {"id": "p1", "statement": "Problem 1", "domain": "ml", "status": "open"},
            {"id": "p2", "statement": "Problem 2", "status": "open"},
        ]
        text = agent._format_problems(candidates)
        assert "1." in text
        assert "2." in text
        assert "Problem 1" in text
        assert "[ml]" in text
