"""
Tests for agentic_kg.agents.state.

Generated by test-generator agent.
"""

import uuid

import pytest

from agentic_kg.agents.schemas import (
    CheckpointDecision,
    CheckpointType,
    HumanCheckpoint,
    WorkflowStatus,
)
from agentic_kg.agents.state import (
    ResearchState,
    add_checkpoint,
    add_error,
    add_message,
    create_initial_state,
)


# =============================================================================
# create_initial_state
# =============================================================================


class TestCreateInitialState:
    """Tests for create_initial_state."""

    def test_default_state(self):
        """Default state has expected keys and values."""
        state = create_initial_state()
        assert state["status"] == WorkflowStatus.PENDING.value
        assert state["current_step"] == ""
        assert state["max_problems"] == 20
        assert state["min_confidence"] == 0.3
        assert state["ranked_problems"] == []
        assert state["messages"] == []
        assert state["errors"] == []
        assert state["selected_problem_id"] is None
        assert state["proposal"] is None
        assert state["proposal_approved"] is False

    def test_generates_unique_run_id(self):
        """Each call generates a unique run_id."""
        s1 = create_initial_state()
        s2 = create_initial_state()
        assert s1["run_id"] != s2["run_id"]
        # Verify it's a valid UUID
        uuid.UUID(s1["run_id"])

    def test_with_filters(self):
        """Filters are stored in state."""
        state = create_initial_state(
            domain_filter="physics",
            status_filter="open",
            max_problems=10,
            min_confidence=0.5,
        )
        assert state["domain_filter"] == "physics"
        assert state["status_filter"] == "open"
        assert state["max_problems"] == 10
        assert state["min_confidence"] == 0.5

    def test_timestamps_are_iso_format(self):
        """Timestamps are ISO format strings."""
        state = create_initial_state()
        # Should not raise
        from datetime import datetime
        datetime.fromisoformat(state["created_at"])
        datetime.fromisoformat(state["updated_at"])


# =============================================================================
# add_message
# =============================================================================


class TestAddMessage:
    """Tests for add_message."""

    def test_appends_message(self):
        """Message is appended to messages list."""
        state = create_initial_state()
        new_state = add_message(state, "ranking", "Found 5 problems")
        assert len(new_state["messages"]) == 1
        assert new_state["messages"][0]["agent"] == "ranking"
        assert new_state["messages"][0]["content"] == "Found 5 problems"
        assert "timestamp" in new_state["messages"][0]

    def test_does_not_mutate_original(self):
        """Original state is not mutated."""
        state = create_initial_state()
        new_state = add_message(state, "test", "msg")
        assert len(state["messages"]) == 0
        assert len(new_state["messages"]) == 1

    def test_updates_updated_at(self):
        """updated_at is refreshed."""
        state = create_initial_state()
        old_updated = state["updated_at"]
        new_state = add_message(state, "test", "msg")
        # Could be same if fast, but should exist
        assert "updated_at" in new_state

    def test_preserves_existing_messages(self):
        """Existing messages are preserved."""
        state = create_initial_state()
        state = add_message(state, "agent1", "first")
        state = add_message(state, "agent2", "second")
        assert len(state["messages"]) == 2
        assert state["messages"][0]["agent"] == "agent1"
        assert state["messages"][1]["agent"] == "agent2"

    def test_handles_missing_messages_key(self):
        """Works even if messages key is missing."""
        state: ResearchState = {"run_id": "test"}  # type: ignore
        new_state = add_message(state, "agent", "content")
        assert len(new_state["messages"]) == 1


# =============================================================================
# add_checkpoint
# =============================================================================


class TestAddCheckpoint:
    """Tests for add_checkpoint."""

    def test_appends_checkpoint(self):
        """Checkpoint is appended as serialized dict."""
        state = create_initial_state()
        cp = HumanCheckpoint(
            checkpoint_type=CheckpointType.SELECT_PROBLEM,
            decision=CheckpointDecision.APPROVE,
        )
        new_state = add_checkpoint(state, cp)
        assert len(new_state["human_checkpoints"]) == 1
        assert new_state["human_checkpoints"][0]["checkpoint_type"] == "select_problem"

    def test_does_not_mutate_original(self):
        """Original state is not mutated."""
        state = create_initial_state()
        cp = HumanCheckpoint(checkpoint_type=CheckpointType.SELECT_PROBLEM)
        new_state = add_checkpoint(state, cp)
        assert len(state["human_checkpoints"]) == 0


# =============================================================================
# add_error
# =============================================================================


class TestAddError:
    """Tests for add_error."""

    def test_appends_error_and_sets_failed(self):
        """Error is appended and status set to FAILED."""
        state = create_initial_state()
        new_state = add_error(state, "Something broke")
        assert "Something broke" in new_state["errors"]
        assert new_state["status"] == WorkflowStatus.FAILED.value

    def test_preserves_existing_errors(self):
        """Existing errors are preserved."""
        state = create_initial_state()
        state = add_error(state, "first error")
        state = add_error(state, "second error")
        assert len(state["errors"]) == 2

    def test_does_not_mutate_original(self):
        """Original state is not mutated."""
        state = create_initial_state()
        new_state = add_error(state, "error")
        assert len(state["errors"]) == 0
