"""
Tests for agentic_kg.agents.synthesis.

Generated by test-generator agent.
"""

from types import SimpleNamespace
from unittest.mock import MagicMock

import pytest

from agentic_kg.agents.schemas import GraphUpdate, SynthesisReport
from agentic_kg.agents.synthesis import SynthesisAgent


class TestSynthesisAgent:
    """Tests for SynthesisAgent."""

    @pytest.fixture
    def agent(self, mock_llm, mock_repo, mock_search, mock_relations):
        return SynthesisAgent(
            llm_client=mock_llm,
            repository=mock_repo,
            search_service=mock_search,
            relation_service=mock_relations,
        )

    @pytest.fixture
    def synthesis_report(self):
        return SynthesisReport(
            summary="Investigation of GNN scalability yielded promising approaches via subgraph sampling.",
            new_problems=["Can importance sampling be applied to heterogeneous graphs?"],
            new_relations=[
                {"source_id": "prob-1", "target_id": "prob-2", "type": "RELATED_TO"},
            ],
            source_problem_id="prob-1",
            recommendations=["Run on larger datasets"],
        )

    def test_name(self, agent):
        assert agent.name == "synthesis"

    @pytest.mark.asyncio
    async def test_run_happy_path(self, agent, mock_llm, synthesis_report, state_with_evaluation):
        """Run generates report and applies graph updates."""
        mock_llm.structured_extract.return_value = SimpleNamespace(content=synthesis_report)

        result = await agent.run(state_with_evaluation)

        assert result["synthesis_report"] is not None
        assert result["status"] == "completed"
        # Should have created problem + relation for new_problems, plus the explicit relation
        mock_repo = agent.repo
        mock_repo.create_problem.assert_called_once()
        agent.relations.create_relation.assert_called()

    @pytest.mark.asyncio
    async def test_run_missing_evaluation(self, agent, state_with_selected_problem):
        """Returns error when evaluation data is missing."""
        result = await agent.run(state_with_selected_problem)
        assert any("Missing evaluation or proposal" in e for e in result["errors"])

    @pytest.mark.asyncio
    async def test_run_missing_proposal(self, agent, initial_state):
        """Returns error when proposal is missing."""
        result = await agent.run(initial_state)
        assert any("Missing" in e for e in result["errors"])

    @pytest.mark.asyncio
    async def test_run_handles_llm_error(self, agent, mock_llm, state_with_evaluation):
        """Handles LLM failure gracefully."""
        mock_llm.structured_extract.side_effect = RuntimeError("LLM fail")

        result = await agent.run(state_with_evaluation)

        assert any("LLM fail" in e for e in result["errors"])

    @pytest.mark.asyncio
    async def test_run_updates_problem_status_on_promising(
        self, agent, mock_llm, mock_repo, synthesis_report, state_with_evaluation
    ):
        """Source problem status updated to in_progress when verdict is promising."""
        mock_llm.structured_extract.return_value = SimpleNamespace(content=synthesis_report)

        result = await agent.run(state_with_evaluation)

        mock_repo.update_problem.assert_called_once()

    @pytest.mark.asyncio
    async def test_run_no_relations_service(self, mock_llm, mock_repo, state_with_evaluation):
        """Works without relation service (no relation creation)."""
        agent = SynthesisAgent(
            llm_client=mock_llm,
            repository=mock_repo,
            search_service=None,
            relation_service=None,
        )
        report = SynthesisReport(
            summary="Investigation completed with no new relations to create in this case.",
            new_problems=["New problem discovered"],
            new_relations=[],
            source_problem_id="prob-1",
        )
        mock_llm.structured_extract.return_value = SimpleNamespace(content=report)

        result = await agent.run(state_with_evaluation)

        assert result["synthesis_report"] is not None
        assert result["status"] == "completed"

    @pytest.mark.asyncio
    async def test_graph_update_failure_does_not_crash(
        self, agent, mock_llm, mock_repo, synthesis_report, state_with_evaluation
    ):
        """Failures in graph updates are logged but do not crash the agent."""
        mock_repo.create_problem.side_effect = RuntimeError("DB error")
        mock_llm.structured_extract.return_value = SimpleNamespace(content=synthesis_report)

        result = await agent.run(state_with_evaluation)

        # Should still complete (errors are logged as warnings, not raised)
        assert result["synthesis_report"] is not None
