"""
Tests for agentic_kg.agents.workflow.

Generated by test-generator agent.
"""

from unittest.mock import AsyncMock, MagicMock

import pytest

from agentic_kg.agents.workflow import (
    _should_continue_after_approve,
    _should_continue_after_review,
    _should_continue_after_select,
    build_workflow,
)


# =============================================================================
# Routing Functions
# =============================================================================


class TestRoutingFunctions:
    """Tests for conditional routing functions."""

    def test_select_continues_when_problem_selected(self):
        """Routes to continuation when problem is selected."""
        state = {"selected_problem_id": "prob-1"}
        assert _should_continue_after_select(state) == "continuation"

    def test_select_ends_when_no_problem(self):
        """Routes to end when no problem selected."""
        state = {"selected_problem_id": None}
        assert _should_continue_after_select(state) == "end"

    def test_select_ends_when_key_missing(self):
        """Routes to end when key is missing."""
        assert _should_continue_after_select({}) == "end"

    def test_approve_continues_when_approved(self):
        """Routes to evaluation when proposal approved."""
        state = {"proposal_approved": True}
        assert _should_continue_after_approve(state) == "evaluation"

    def test_approve_ends_when_not_approved(self):
        """Routes to end when proposal not approved."""
        state = {"proposal_approved": False}
        assert _should_continue_after_approve(state) == "end"

    def test_review_continues_when_approved(self):
        """Routes to synthesis when evaluation approved."""
        state = {"evaluation_approved": True}
        assert _should_continue_after_review(state) == "synthesis"

    def test_review_ends_when_not_approved(self):
        """Routes to end when evaluation not approved."""
        state = {"evaluation_approved": False}
        assert _should_continue_after_review(state) == "end"


# =============================================================================
# build_workflow
# =============================================================================


class TestBuildWorkflow:
    """Tests for build_workflow graph construction."""

    @pytest.fixture
    def mock_agents(self):
        ranking = MagicMock()
        ranking.run = AsyncMock()
        continuation = MagicMock()
        continuation.run = AsyncMock()
        evaluation = MagicMock()
        evaluation.run = AsyncMock()
        synthesis = MagicMock()
        synthesis.run = AsyncMock()
        return ranking, continuation, evaluation, synthesis

    def test_build_returns_compiled_graph(self, mock_agents):
        """build_workflow returns a compiled graph object."""
        graph = build_workflow(*mock_agents)
        assert graph is not None

    def test_build_with_custom_checkpointer(self, mock_agents):
        """build_workflow accepts a custom checkpointer."""
        from langgraph.checkpoint.memory import MemorySaver
        checkpointer = MemorySaver()
        graph = build_workflow(*mock_agents, checkpointer=checkpointer)
        assert graph is not None

    def test_graph_has_expected_nodes(self, mock_agents):
        """Compiled graph includes all expected node names."""
        graph = build_workflow(*mock_agents)
        # LangGraph compiled graphs have a .nodes attribute or similar
        # We verify the graph was built without error (structure tested via routing)
        assert graph is not None
