"""
Tests for agentic_kg.agents.config.

Generated by test-generator agent.
"""

import pytest

from agentic_kg.agents.config import (
    AgentConfig,
    AgentLLMConfig,
    CheckpointConfig,
    SandboxConfig,
    get_agent_config,
    reset_agent_config,
)


# =============================================================================
# AgentLLMConfig
# =============================================================================


class TestAgentLLMConfig:
    """Tests for AgentLLMConfig dataclass."""

    def test_defaults(self):
        """Default values are set correctly."""
        cfg = AgentLLMConfig()
        assert cfg.model == "gpt-4o"
        assert cfg.temperature == 0.3
        assert cfg.max_tokens == 4096

    def test_custom_values(self):
        """Custom values override defaults."""
        cfg = AgentLLMConfig(model="claude-3", temperature=0.7, max_tokens=8192)
        assert cfg.model == "claude-3"
        assert cfg.temperature == 0.7


# =============================================================================
# SandboxConfig
# =============================================================================


class TestSandboxConfig:
    """Tests for SandboxConfig dataclass."""

    def test_defaults(self, monkeypatch):
        """Default values when env vars are not set."""
        monkeypatch.delenv("SANDBOX_IMAGE", raising=False)
        monkeypatch.delenv("SANDBOX_TIMEOUT", raising=False)
        monkeypatch.delenv("SANDBOX_MEMORY", raising=False)
        monkeypatch.delenv("SANDBOX_CPU", raising=False)
        cfg = SandboxConfig()
        assert cfg.image == "python:3.12-slim"
        assert cfg.timeout_seconds == 300
        assert cfg.memory_limit == "2g"
        assert cfg.cpu_limit == 1.0
        assert cfg.network_disabled is True
        assert cfg.read_only_rootfs is True
        assert "numpy" in cfg.pip_packages

    def test_from_env(self, monkeypatch):
        """Values loaded from environment variables."""
        monkeypatch.setenv("SANDBOX_IMAGE", "python:3.11")
        monkeypatch.setenv("SANDBOX_TIMEOUT", "60")
        monkeypatch.setenv("SANDBOX_MEMORY", "4g")
        monkeypatch.setenv("SANDBOX_CPU", "2.0")
        cfg = SandboxConfig()
        assert cfg.image == "python:3.11"
        assert cfg.timeout_seconds == 60
        assert cfg.memory_limit == "4g"
        assert cfg.cpu_limit == 2.0


# =============================================================================
# CheckpointConfig
# =============================================================================


class TestCheckpointConfig:
    """Tests for CheckpointConfig dataclass."""

    def test_all_enabled_by_default(self):
        """All checkpoints are required by default."""
        cfg = CheckpointConfig()
        assert cfg.require_problem_selection is True
        assert cfg.require_proposal_approval is True
        assert cfg.require_evaluation_review is True

    def test_can_disable(self):
        """Checkpoints can be disabled."""
        cfg = CheckpointConfig(require_problem_selection=False)
        assert cfg.require_problem_selection is False


# =============================================================================
# AgentConfig
# =============================================================================


class TestAgentConfig:
    """Tests for AgentConfig dataclass."""

    def test_defaults(self):
        """Sub-configs have expected agent-specific defaults."""
        cfg = AgentConfig()
        assert cfg.ranking.temperature == 0.2
        assert cfg.continuation.temperature == 0.5
        assert cfg.continuation.max_tokens == 8192
        assert cfg.evaluation.temperature == 0.2
        assert cfg.synthesis.temperature == 0.3

    def test_sandbox_included(self):
        """Sandbox config is included."""
        cfg = AgentConfig()
        assert isinstance(cfg.sandbox, SandboxConfig)

    def test_checkpoints_included(self):
        """Checkpoint config is included."""
        cfg = AgentConfig()
        assert isinstance(cfg.checkpoints, CheckpointConfig)


# =============================================================================
# Singleton
# =============================================================================


class TestGetAgentConfig:
    """Tests for get_agent_config singleton."""

    def test_returns_same_instance(self):
        """Singleton returns same object."""
        reset_agent_config()
        c1 = get_agent_config()
        c2 = get_agent_config()
        assert c1 is c2

    def test_reset_clears_singleton(self):
        """Reset creates a new instance."""
        reset_agent_config()
        c1 = get_agent_config()
        reset_agent_config()
        c2 = get_agent_config()
        assert c1 is not c2
